# Generated by Django 5.2.8 on 2025-11-10 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('read_order', 'Can read orders'), ('manage_order', 'Can manage orders')]},
        ),
    ]
