# Generated by Django 5.2.8 on 2025-11-10 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('read_category', 'Can read categories'), ('manage_category', 'Can manage categories')], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='inventorymovement',
            options={'ordering': ['-created_at'], 'permissions': [('read_inventorymovement', 'Can read inventory movements'), ('manage_inventorymovement', 'Can manage inventory movements')]},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('read_product', 'Can read products'), ('manage_product', 'Can manage products')]},
        ),
    ]
