# Generated by Django 5.2.8 on 2025-11-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_address_user_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Firebase Cloud Messaging device token for push notifications', max_length=255, null=True),
        ),
    ]
