// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7WRXeWOCzlJBvY37ceUyH-vPaeNEUL4c',
    appId: '1:849943100563:web:d9545e6efd4c8eca426166',
    messagingSenderId: '849943100563',
    projectId: 'sistemaboutique-5f9d1',
    authDomain: 'sistemaboutique-5f9d1.firebaseapp.com',
    storageBucket: 'sistemaboutique-5f9d1.firebasestorage.app',
    measurementId: 'G-4SMTCRR1ZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGHS24jjs42wAr5OwV0X9vMPTJYbT456c',
    appId: '1:849943100563:android:88e129474d20ecc5426166',
    messagingSenderId: '849943100563',
    projectId: 'sistemaboutique-5f9d1',
    storageBucket: 'sistemaboutique-5f9d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwY0do0uB2Ld7dF0xNzLkbm9FsCZmq1nQ',
    appId: '1:849943100563:ios:dcb21bab2a8b8e22426166',
    messagingSenderId: '849943100563',
    projectId: 'sistemaboutique-5f9d1',
    storageBucket: 'sistemaboutique-5f9d1.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwY0do0uB2Ld7dF0xNzLkbm9FsCZmq1nQ',
    appId: '1:849943100563:ios:dcb21bab2a8b8e22426166',
    messagingSenderId: '849943100563',
    projectId: 'sistemaboutique-5f9d1',
    storageBucket: 'sistemaboutique-5f9d1.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7WRXeWOCzlJBvY37ceUyH-vPaeNEUL4c',
    appId: '1:849943100563:web:78b97459833bd68a426166',
    messagingSenderId: '849943100563',
    projectId: 'sistemaboutique-5f9d1',
    authDomain: 'sistemaboutique-5f9d1.firebaseapp.com',
    storageBucket: 'sistemaboutique-5f9d1.firebasestorage.app',
    measurementId: 'G-S8X3CBXEMY',
  );
}
