import 'package:flutter/material.dart';
import 'package:intl/date_symbol_data_local.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart'; // Import Firebase Core
import 'package:firebase_messaging/firebase_messaging.dart'; // Import Firebase Messaging

import 'package:mobile/providers/notification_provider.dart';

import 'package:mobile/services/local_notification_service.dart';



import 'app.dart';

import 'providers/auth_provider.dart';

import 'providers/cart_provider.dart';

import 'providers/order_provider.dart';

import 'providers/product_provider.dart';

import 'firebase_options.dart'; // Will be generated by FlutterFire CLI



// Handler for background messages

Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {

  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  print("Handling a background message: ${message.messageId}");

  // Here you could also show a local notification if needed

}



void main() async {

  WidgetsFlutterBinding.ensureInitialized();

  

  // Initialize Firebase

  await Firebase.initializeApp(

    options: DefaultFirebaseOptions.currentPlatform,

  );



  // Initialize Local Notification Service

  LocalNotificationService.initialize();



  // Set up background message handler

  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);



  // Request notification permissions

  NotificationSettings settings = await FirebaseMessaging.instance.requestPermission(

    alert: true,

    announcement: false,

    badge: true,

    carPlay: false,

    criticalAlert: false,

    provisional: false,

    sound: true,

  );



  print('User granted permission: ${settings.authorizationStatus}');



    // Get FCM token

    String? fcmToken = await FirebaseMessaging.instance.getToken();

    print("FCM Token: $fcmToken");

  

    initializeDateFormatting('es_ES', null).then((_) {

      runApp(AppWrapper(fcmToken: fcmToken)); // Pass fcmToken to AppWrapper

    });

  }



class AppWrapper extends StatelessWidget {

  final String? fcmToken;



  const AppWrapper({super.key, this.fcmToken});



  @override

  Widget build(BuildContext context) {

    return MultiProvider(

      providers: [

        ChangeNotifierProvider(

          create: (_) => AuthProvider()..initialize(fcmToken: fcmToken),

        ),

        ChangeNotifierProvider(create: (_) => CartProvider()),

        ChangeNotifierProxyProvider<AuthProvider, ProductProvider>(

          create: (_) => ProductProvider(),

          update: (_, auth, previous) => previous!..fetchAllProducts(),

        ),

        ChangeNotifierProxyProvider<AuthProvider, OrderProvider>(

          create: (context) => OrderProvider(

            authProvider: Provider.of<AuthProvider>(context, listen: false),

          ),

          update: (_, auth, previous) => previous!..fetchUserOrders(),

        ),

        ChangeNotifierProxyProvider<AuthProvider, NotificationProvider>(

          create: (context) => NotificationProvider(

            authProvider: Provider.of<AuthProvider>(context, listen: false),

          ),

          update: (_, auth, previous) => previous!..fetchNotifications(),

        ),

      ],

      child: const BoutiqueApp(),

    );

  }

}